#!/usr/bin/env bash

# resolve links - $0 may be a soft link
PRG="$0"

while [ -h "$PRG" ]; do
  ls=`ls -ld "${PRG}"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "${PRG}"`/"$link"
  fi
done

# Get standard environment variables
PRGDIR=`dirname "${PRG}"`

: ${WS_HOME:="$HOME/.ws"}

mkdir -p $WS_HOME
cp -R $PRGDIR/ $WS_HOME
rm -f $WS_HOME/install

if [ -e ~/.bash_profile ]
then
    cat <<- EOF >> ~/.bash_profile
	# WS-Start
	export WS_HOME=$WS_HOME
	export PATH=\$WS_HOME/bin:\$PATH
	# WS-End
EOF
fi

cat <<- EOF > $WS_HOME/uninstall
: ${WS_HOME:="$WS_HOME"}
rm -fr $WS_HOME
cd

if [ -e ~/.bash_profile ]
then
    sed -i .bak '/# WS-Start/,/# WS-End/d' ~/.bash_profile
fi
EOF
chmod 755 $WS_HOME/uninstall
